### ISSUE TITLE
Cannot run Cooper

### ISSUE THREAD

**Issue by CyberM070** [chrismaddalena/Cooper#22]
Hi Chris,

I'm really keen about this tool but I can't run it because of the following:

python3 cooper.py -t https://portal.office.com
Traceback (most recent call last):
  File "cooper.py", line 27, in <module>
    from lib import toolbox # Import the custom Toolbox class
  File "/opt/cooper/lib/toolbox.py", line 28, in <module>
    from selenium import webdriver 	# Used for alternative HTML source collection
ModuleNotFoundError: No module named 'selenium' 

All dependencies are installed correctly. 

Do you know a way to resolve this?

**Comment by chrismaddalena** [comment]
It looks like the dependencies are not installed for your `python3`. You may have Selenium and the rest installed but they won't be found unless you used the `pip` command that is tied to `python3` on your system. Try installing the requirements with: `python3 -m pip install -r requirements.txt`

**Comment by CyberM070** [comment]
Worked like a charm, thanks once more!
